PandaBook/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace PandaBook.Models
{
    public class Stock
    {
        public Stock(String name, String code, String source)
        {
            this.name = name;
            this.code = code;
            this.source = source;
        }
        public int StockId { get; set; }
        public string source { get; set; }
        public string code { get; set; }
        public string name { get; set; }
    }

    public class StockDBContext : DbContext
    {
        public DbSet<Stock> Stocks { get; set; }
    }
}

PandaBook/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;
using System.Net;
using System.Web.UI.DataVisualization.Charting;
using PandaBook.Models;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Globalization;
using System.Web.Script.Serialization;
using System.Text;

namespace PandaBook.Controllers
{
    public class StockController : Controller
    {
        private static String[] tokens = new String[] { "uK8GHKPJykvk1xHxzYR9", "uK8GHKPJykvk1xHxzYR9" };
        private static Hashtable curQuotes = null;
        private static String lastUpdate = "";
        private static String[] curCodes = new String[] { };
        private static StockDBContext db = new StockDBContext();

        /**
         * Adds a stock to the database with given values and then reloads the instance of the database
         * 
         * @author Conor Wright
         * @param stock - a stock element with information for the new stock entry in the table
         */
        public static void addStock(Stock stock)
        {
            using (SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["StockDB"].ConnectionString))
            {
                try
                {
                    connection.Open();
                    SqlCommand cmd = new SqlCommand("INSERT INTO Stocks(Name, Code, Source) VALUES (@Name, @Code, @Source)");
                    cmd.CommandType = CommandType.Text;
                    cmd.Connection = connection;
                    cmd.Parameters.AddWithValue("@Name", stock.name.Replace('`',' '));
                    cmd.Parameters.AddWithValue("@Code", stock.code.Replace('`', ' '));
                    cmd.Parameters.AddWithValue("@Source", stock.source.Replace('`', ' '));
                    cmd.ExecuteNonQuery();
                    connection.Close();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.ToString());
                }
            }
            db = new StockDBContext();
        }

        /**
         * Sells given stock in the database and then reloads the instance of the database
         * 
         * @author Conor Wright
         * @param stock - a stock element to sell
         * @param shares - Quantity of stock to sell
         */
        public static String sellStock(int UserId, Stock stock, int shares)
        {
            int rar = -1;
            using (SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["StockDB"].ConnectionString))
            {
                try
                {
                    connection.Open();
                    SqlCommand cmd = new SqlCommand("SELECT SUM(Quantity) AS Totes from Transactions WHERE UserID=@User AND StockID=(SELECT TOP 1 Id FROM Stocks Where Code=@Stock);");
                    cmd.CommandType = CommandType.Text;
                    cmd.Connection = connection;
                    cmd.Parameters.AddWithValue("@User", UserId);
                    cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                    object dat = cmd.ExecuteScalar();
                    int result = dat != null ? (int)dat : 0;
                    connection.Close();

                    if (result < shares)
                    {
                        connection.Open();
                        cmd = new SqlCommand("DELETE FROM Transactions WHERE UserID=@User AND StockID=(SELECT TOP 1 Id FROM Stocks WHERE Code=@Stock);");
                        cmd.CommandType = CommandType.Text;
                        cmd.Connection = connection;
                        cmd.Parameters.AddWithValue("@User", UserId);
                        cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                        result = cmd.ExecuteNonQuery();
                        connection.Close();
                    }
                    else
                    {
                        int x = shares;
                        while (x > 0)
                        {
                            connection.Open();
                            cmd = new SqlCommand("UPDATE Transactions SET Quantity=Quantity-1 FROM Transactions WHERE Id = (SELECT Top 1 Id FROM Transactions Where UserId = @User AND StockId = (SELECT TOP 1 Id FROM Stocks WHERE Stocks.Code=@Stock) ORDER BY Date ASC);");
                            cmd.CommandType = CommandType.Text;
                            cmd.Connection = connection;
                            cmd.Parameters.AddWithValue("@User", UserId);
                            cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                            result = cmd.ExecuteNonQuery();
                            connection.Close();
                            connection.Open();
                            cmd = new SqlCommand("DELETE FROM Transactions WHERE Quantity=0;");
                            cmd.CommandType = CommandType.Text;
                            cmd.Connection = connection;
                            result = cmd.ExecuteNonQuery();
                            connection.Close();
                            x = x - 1;
                            Debug.WriteLine(x + " " + (x > 0));
                        }
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine("Panda: " + e.ToString());
                }
            }
            db = new StockDBContext();
            return "Pandas: " + rar;
        }

        /**
         * Buys given stock in the database and then reloads the instance of the database
         * 
         * @author Conor Wright
         * @param stock - a stock element to Buy
         * @param shares - Quantity of stock to buy
         * @param date - When the stock was bought
         */
        public static String buyStock(int UserId, Stock stock, int shares, DateTime date)
        {
            int rar = -1;
            using (SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["StockDB"].ConnectionString))
            {
                try
                {
                    connection.Open();
                    SqlCommand cmd = new SqlCommand("SELECT COUNT(*) AS Totes FROM Transactions WHERE UserID=@User AND StockID=(SELECT TOP 1 Id FROM Stocks WHERE Stocks.Code=@Stock) AND Date=@Date;");
                    cmd.CommandType = CommandType.Text;
                    cmd.Connection = connection;
                    cmd.Parameters.AddWithValue("@User", UserId);
                    cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                    cmd.Parameters.AddWithValue("@Date", date.ToString("yyyy-MM-dd"));
                    object dat = cmd.ExecuteScalar();
                    int result = dat != null ? (int)dat : 0;
                    connection.Close();

                    if (result == 0)
                    {
                        connection.Open();
                        cmd = new SqlCommand("INSERT INTO Transactions(UserID, StockID, Quantity, Date) VALUES(@User,(SELECT TOP 1 Id FROM Stocks WHERE Code=@Stock),@Quantity,@Date);");
                        cmd.CommandType = CommandType.Text;
                        cmd.Connection = connection;
                        cmd.Parameters.AddWithValue("@User", UserId);
                        cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                        cmd.Parameters.AddWithValue("@Quantity", shares);
                        cmd.Parameters.AddWithValue("@Date", date.ToString("yyyy-MM-dd"));
                        result = cmd.ExecuteNonQuery();
                        connection.Close();
                    }
                    else
                    {
                        connection.Open();
                        cmd = new SqlCommand("UPDATE Transactions SET Quantity=@Quantity+Quantity FROM Transactions WHERE UserId = @User AND StockId = (SELECT TOP 1 Id FROM Stocks WHERE Stocks.Code=@Stock) AND Date=@Date;");
                        cmd.CommandType = CommandType.Text;
                        cmd.Connection = connection;
                        cmd.Parameters.AddWithValue("@User", UserId);
                        cmd.Parameters.AddWithValue("@Stock", stock.code.Replace('`', ' '));
                        cmd.Parameters.AddWithValue("@Quantity", shares);
                        cmd.Parameters.AddWithValue("@Date", date.ToString("yyyy-MM-dd"));
                        result = cmd.ExecuteNonQuery();
                        connection.Close();
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine("Panda: "+e.ToString());
                }
            }
            db = new StockDBContext();
            return "Pandas: " + rar;
        }

        /**
         * Checks if current stock is favorited
         * 
         * @author Conor Wright
         * @param stock - a stock element to check favorite status of
         */
        public static Boolean isFavorite(int UserId, Stock stock)
        {
            Boolean ret = false;
            using (SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["StockDB"].ConnectionString))
            {
                try
                {
                    connection.Open();
                    SqlCommand cmd = new SqlCommand("SELECT COUNT(*) AS Totes FROM Notes WHERE UserID=@User AND StockID=(SELECT TOP 1 Id FROM Stocks WHERE Stocks.Code=@Stock);");
                    cmd.CommandType = CommandType.Text;
                    cmd.Connection = connection;
                    cmd.Parameters.AddWithValue("@User", UserId);

PandaBook/Views/Stock/MyData.cshtml
@{
    Layout = null;
    this.Write(ViewBag.data.ToString());
}

PandaBook/Views/Stock/Stock.cshtml
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-50657305-1', 'rit.edu');
    ga('send', 'pageview');

</script>
@{
    if(ViewBag.code != "" && ViewBag.code != null && ViewBag.count!=0){
        ViewBag.Title = ViewBag.code+" Stock";
    }
    else
    {
        ViewBag.Title = "Stock Not Found";
    }
    var hsh = ViewBag.data;
    String k = "";
    double preD = 0;
    int count = 0;
    String changeColor = "black";
    double d = 0;
    try { 
        foreach (String key in ViewBag.keys)
        {
            if(count==0){
                k = key;
            }
            else{
                preD = Math.Round(hsh[k] - hsh[key], 2);
                break;
            }
            count+=1;
        }
        d = Math.Round(hsh[k], 2);
        if (preD < 0)
        {
            changeColor = "red";
        }
        else if (preD > 0)
        {
            changeColor = "green";
        }
    }
    catch (Exception e)
    { Console.WriteLine(e.ToString()); }
}
<meta property="og:image" content="./StockChart?code=@ViewBag.code"/>
<div id="stockDrawer">
    <div class="roundside">
        <div>
            <label>Search Stock Code: </label>
            <input id="changeStock" type="text" placeholder="Stock Code" onkeydown="if (event.keyCode == 13) document.getElementById('submitChangeStock').click()">
            <button id="submitChangeStock" title="Submit" class="btn btn-default" onclick="window.location.href = './Stock?code=' + $('#changeStock').val()">Submit</button>
        </div>
        <ul class="nav nav-pills nav-stacked span2">
            @Html.Raw(ViewBag.listOStocks);
        </ul>
    </div>
    <div class="roundbottom"></div>
</div><div id="drawerTab"><b>»</b></div>
<div class="jumbotron stockotron">
    <div id="heart" title="favorite stock?" onclick="favorite('@ViewBag.code', ($('#heart .aft').css('background-color')!='rgb(255, 0, 0)' && $('#heart .aft').css('background-color')!='rgb(255, 51, 51)'))"><div class="bef"></div><div class="aft"></div></div>
    <h2 id="datStockHeader" title="http://localhost:28202/Stock/Stock?code=AAPL">@ViewBag.Title</h2>
    <script type="text/javascript">
        document.getElementById("datStockHeader").setAttribute('title', window.location.href);
    </script>
        <img id="datChartDoh" style="text-align: center; height: 80%; width:90%;" src="./StockChart?code=@ViewBag.code"><br>
        <div id="chartChanger">
            <input id="date1" class="inputs" placeholder="yyyy-MM-dd">
            <button id="updateChart" onclick="updateChart('@ViewBag.code', $('#date1').val(), $('#date2').val());" class="btn btn-default">Update Chart</button>
            <input id="date2" class="inputs" placeholder="yyyy-MM-dd">
        </div>
        <div class="row" style="width: 90% padding: 14px 24px; font-size: 21px;">
            <div class="col-sm-4" style="text-align: center; width: 100%; padding: 14px 24px; font-size: 21px;">
                <ul class="list-group" style="text-align: center; width: 100%; padding: 14px 24px; font-size: 21px; ">
                    <li class="list-group-item"><label>Current Quote: </label><b> @d</b></li>
                    <li class="list-group-item"><label>Recent Change: </label><b id="SPChangeVal" style="color:@changeColor"> @preD</b></li>
                    <li class="list-group-item"><label>Change Date: </label><b> @k</b></li>
                    <li id="shareSet" class="list-group-item"><label>Shares Owned: </label><b> @ViewBag.shareCount</b></li>
                </ul>
                <div id="transactions">
                    <button id="buyButton" onclick="buy('@ViewBag.code', $('#shareCount').val())" class="btn btn-default">Buy</button>
                    <input id="shareCount" class="inputs" title="Number of Shares" type="text">
                    <button id="sellButton" onclick="sell('@ViewBag.code', $('#shareCount').val())" class="btn btn-default">Sell</button>
                </div>
                <button class="btn btn-default" onclick="FB.ui({
        method: 'feed',
            link: $('.stockotron h2').attr('title'),
        caption: $('.stockotron h2').text(),
        }, function(response){});" style="color: white; background-color: blue; float: right;">
        <b>Share</b>
    </button>
</div><!-- /.col-sm-4 -->
</div>
</div>
<div id="noteSection" style="padding-bottom: 10px;">
    <div id="notePanel" class="radius">View Note</div>
    <div id="datNote" class="radius" style="padding-bottom: 10px;">
        <div id="note1">
            <p>@ViewBag.note</p>
            <button class="superButton" onclick="$('#note1').css('display', 'none'); $('#note2').css('display', 'block'); $('#note2 input').val($('#note1 p').html());">Edit Note</button>
        </div>
        <div id="note2" style="display: none">
            <textarea style="height: 90px; width: 90%;"></textarea>
            <button class="superButton" onclick="$('#note2').css('display', 'none'); $('#note1').css('display', 'block');">Cancel</button>
            <button class="superButton" onclick="$('#note2').css('display', 'none'); $('#note1').css('display', 'block'); setNote('@ViewBag.code', $('#note2 textarea').val());">Submit</button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#notePanel").click(function () {
        $("#datNote").slideToggle("slow");
    });
    $("#heart .bef").css("background", '@ViewBag.isFavored');
    $("#heart .aft").css("background", '@ViewBag.isFavored');
    $("#heart .bef").hover(function () {
        var tempting = $("#heart .bef").css("background-color");
        $("#heart .bef").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(51, 51, 255)' : 'rgb(255, 51, 51)');
        $("#heart .aft").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(51, 51, 255)' : 'rgb(255, 51, 51)');
        
    }, function () {
        var tempting = $("#heart .bef").css("background-color");
        $("#heart .bef").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(0, 0, 255)' : 'rgb(255, 0, 0)');
        $("#heart .aft").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(0, 0, 255)' : 'rgb(255, 0, 0)');
    });
    $("#heart .aft").hover(function () {
        var tempting = $("#heart .bef").css("background-color");
        $("#heart .bef").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(51, 51, 255)' : 'rgb(255, 51, 51)');
        $("#heart .aft").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(51, 51, 255)' : 'rgb(255, 51, 51)');

    }, function () {
        var tempting = $("#heart .bef").css("background-color");
        $("#heart .bef").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(0, 0, 255)' : 'rgb(255, 0, 0)');
        $("#heart .aft").css("background-color", (tempting == "rgb(0, 0, 255)" || tempting == 'rgb(51, 51, 255)') ? 'rgb(0, 0, 255)' : 'rgb(255, 0, 0)');
    });
    $("#drawerTab").click(function () {
        var pos = $("#stockDrawer").position();
        if (!$("#stockDrawer").hasClass("expanded")) {
            $("#stockDrawer").stop(true, false).animate({
                left: "15.8%"
            });
            $("#drawerTab").stop(true, false).animate({
                left: "45.8%"
            });
            $("#stockDrawer").addClass("expanded");
            $("#drawerTab b").text("«");
        }
        else {
            $("#stockDrawer").stop(true, false).animate({
                left: "-14.2%"
            });
            $("#drawerTab").stop(true, false).animate({
                left: "15.8%"
            });
            $("#stockDrawer").removeClass("expanded");
            $("#drawerTab b").text("»");
        }
    });
    </script>

PandaBook/Views/Stock/StockChart.cshtml
@{
    ViewBag.Title = "Stock Chart";
    var hsh = ViewBag.data;

    /**
     * Generates the stock chart from the data passed in through the ViewBag's data attribute
     * @author - Conor Wright
     * @param data - a Hashtable of data to graph
     * @return Chart - the mapped data
     */
    String[] keys = new String[hsh.Count];
    double[] values = new double[hsh.Count];
    int count = 0;
    foreach (String key in hsh.Keys)
    {
        keys[count] = key;
        values[count] = hsh[key];
        count += 1;
    }
    Array.Sort<String>(keys);
    count = 0;
    foreach (String key in keys)
    {
        values[count] = hsh[key];
        count += 1;
    }
    var myChart = new Chart(width: 600, height: 400) 
       .AddTitle("Stock Chart") 
       .AddSeries(chartType: "line",
          xValue: keys, 
          yValues: values) 
       .Write();
}

PandaBook/Views/Stock/StockData.cshtml
@{
    ViewBag.Title = "StockData";
}

<h2 style="margin-left: 19%;">StockData</h2>
<div id="downloadSection" class="jumbotron">
    <h3>Download Transaction History</h3>
       <a class="superButton" href="MyData" download="MyStockData.yoho">Download</a>
</div>
<div id="uploadSection" class="jumbotron" style="margin-top:20px">
    <h3>Upload Transaction History</h3>
    @using (Html.BeginForm("Upload", "Stock", FormMethod.Post))
    {
    <input type="file" id="fileUpload" style="margin: 0 auto;" />
    <input class="superButton" type="submit" value="Upload" />
    }
</div>

PandaBook/Views/Stock/Upload.cshtml
@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    <div>
        <h1>Success!</h1>
    </div>
</body>
</html>